includes: projects/task/test_vtt.yaml
model:
  model_cls: MMFusionSeparate
  mm_encoder_cls: 
  video_encoder_cls: MMBertForEncoder
  text_encoder_cls: BertModel
  num_hidden_video_layers: 6

  encoder_projector: qformer
  qformer_layers: 6
  query_len: 64

