includes: projects/task/test_coin.yaml
model:
  model_cls: MMFusionSeparateActionSegmentation
  mm_encoder_cls: 
  video_encoder_cls: MMBertForTokenClassification
  text_encoder_cls: BertModel  # dummy, not used.
  num_hidden_video_layers: 6

  encoder_projector: qformer
  qformer_layers: 6
  query_len: 64